# Generated by Django 3.2.5 on 2021-09-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_product_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(choices=[('Pending', 'Pending'), ('out for delivery', 'out for delivery'), ('Delivered', 'Delivered')], max_length=1000, null=True),
        ),
    ]
